# Generated by Django 3.1.6 on 2021-07-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210701_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='year',
            field=models.IntegerField(default=2021),
        ),
    ]
