# Generated by Django 3.1.6 on 2022-02-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20220219_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountaudit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
