# Generated by Django 3.1.6 on 2022-02-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_accountaudit_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountaudit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
