# Generated by Django 3.1.6 on 2022-02-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20220220_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyaudit',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
