# Generated by Django 3.1.6 on 2021-07-02 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_organisation_esea_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eseaaccount',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esea_accounts', to='core.organisation'),
        ),
    ]
