# Generated by Django 3.1.6 on 2021-07-14 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210713_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('denied', 'denied')], max_length=100)),
                ('requester', models.CharField(choices=[('network', 'network'), ('organisation', 'organisation')], max_length=100)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.network')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_requests', to='core.organisation')),
            ],
        ),
        migrations.DeleteModel(
            name='QuestionOption',
        ),
    ]
