# Generated by Django 3.1.6 on 2021-07-16 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210715_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('denied', 'denied')], default='pending', max_length=100)),
                ('role', models.CharField(choices=[(2, 'network admin'), (1, 'guest')], default=1, max_length=100)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teammembers', to='core.network')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
