# Generated by Django 3.1.6 on 2021-08-02 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210728_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directindicator',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_indicators', to='core.topic'),
        ),
    ]
