# Generated by Django 3.1.6 on 2022-02-20 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_surveyaudit_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
