# Generated by Django 3.1.6 on 2021-08-02 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20210802_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directindicator',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_indicator', to='core.question'),
        ),
        migrations.AlterField(
            model_name='directindicator',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_indicators', to='core.topic'),
        ),
    ]
