# Generated by Django 3.1.6 on 2022-01-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20211217_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='certification_theshold',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='year',
            field=models.IntegerField(default=2022),
        ),
        migrations.AlterField(
            model_name='directindicator',
            name='cut_off_lower_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='directindicator',
            name='cut_off_upper_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='eseaaccount',
            name='year',
            field=models.IntegerField(default=2022),
        ),
        migrations.AlterField(
            model_name='indirectindicator',
            name='cut_off_lower_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='indirectindicator',
            name='cut_off_upper_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='indirectindicator',
            name='type',
            field=models.CharField(choices=[('performance', 'performance'), ('scoring', 'scoring'), ('certification', 'certification')], default='scoring', max_length=50),
        ),
    ]
