# Generated by Django 3.1.6 on 2022-02-19 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20220219_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False)),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
                ('assurance', models.CharField(choices=[('limited', 'limited'), ('reasonable', 'reasonable'), ('assurance rejected', 'assurance rejected'), ('no assurance', 'no assurance')], max_length=100)),
                ('esea_account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_audit', to='core.eseaaccount')),
            ],
        ),
    ]
