# Generated by Django 3.1.6 on 2022-02-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20220219_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountaudit',
            name='finished',
        ),
        migrations.AddField(
            model_name='accountaudit',
            name='status',
            field=models.CharField(choices=[('not started', 'not started'), ('in progress', 'in progress'), ('finished', 'finished')], default='not started', max_length=100),
        ),
    ]
