# Generated by Django 3.1.6 on 2022-02-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20220220_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyaudit',
            name='sample_size',
            field=models.IntegerField(null=True),
        ),
    ]
