# Generated by Django 3.1.6 on 2022-02-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20220220_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyaudit',
            name='sample_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
