# Generated by Django 3.1.6 on 2022-03-28 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_questionresponse_auditstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='audit_finish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='audit_start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='auditstatus',
            field=models.CharField(blank=True, choices=[('Not Started', 'Not Started'), ('Organisation Selection', 'Organisation Selection'), ('Audits in Progress', 'Audits in Progress'), ('All Audits Finished', 'All Audits Finished')], default='Not Started', max_length=100),
        ),
    ]
