# Generated by Django 3.1.6 on 2024-08-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_campaign_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='campaign',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='eseaaccount',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
