# Generated by Django 3.1.6 on 2021-07-01 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_campaign_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='esea_accounts',
        ),
    ]
