# Generated by Django 3.1.6 on 2021-07-08 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210707_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.method'),
        ),
    ]
