# Generated by Django 3.1.6 on 2021-07-09 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210708_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='core.question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='directindicator',
            name='datatype',
            field=models.CharField(choices=[('Text', 'Text'), ('Integer', 'Integer'), ('Double', 'Double'), ('Date', 'Date'), ('Boolean', 'Boolean'), ('SingleChoice', 'SingleChoice'), ('MultipleChoice', 'MultipleChoice')], default='TEXT', max_length=50),
        ),
    ]
