# Generated by Django 3.1.6 on 2021-07-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210709_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='values',
            field=models.ManyToManyField(blank=True, related_name='question_responses', to='core.AnswerOption'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='question_responses',
            field=models.ManyToManyField(blank=True, related_name='vals', to='core.QuestionResponse'),
        ),
    ]
