# Generated by Django 3.1.6 on 2021-07-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210709_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directindicator',
            name='datatype',
            field=models.CharField(choices=[('Text', 'Text'), ('Integer', 'Integer'), ('Double', 'Double'), ('Date', 'Date'), ('Boolean', 'Boolean'), ('singleChoice', 'singleChoice'), ('multipleChoice', 'multipleChoice')], default='Text', max_length=50),
        ),
        migrations.AlterField(
            model_name='indirectindicator',
            name='datatype',
            field=models.CharField(choices=[('Text', 'Text'), ('Integer', 'Integer'), ('Double', 'Double'), ('Date', 'Date'), ('Boolean', 'Boolean'), ('singleChoice', 'singleChoice'), ('multipleChoice', 'multipleChoice')], default='Text', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='answertype',
            field=models.CharField(choices=[('Text', 'Text'), ('Number', 'Number'), ('Radio', 'Radio'), ('Checkbox', 'checkBox'), ('Scale', 'scale')], default='Text', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='uiComponent',
            field=models.CharField(choices=[('Field', 'Field'), ('Line', 'Line'), ('Textbox', 'textBox'), ('Checkbox', 'checkBox'), ('Dropdown', 'dropDown'), ('radioButton', 'radioButton')], default='Field', max_length=100),
        ),
    ]
