# Generated by Django 3.1.6 on 2021-07-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210709_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directindicator',
            name='datatype',
            field=models.CharField(choices=[('text', 'text'), ('integer', 'Integer'), ('double', 'double'), ('date', 'date'), ('boolean', 'boolean'), ('singlechoice', 'singlechoice'), ('multipleChoice', 'multiplechoice')], default='text', max_length=50),
        ),
        migrations.AlterField(
            model_name='indirectindicator',
            name='datatype',
            field=models.CharField(choices=[('text', 'text'), ('integer', 'integer'), ('double', 'double'), ('date', 'date'), ('boolean', 'boolean'), ('singlechoice', 'singlechoice'), ('multiplechoice', 'multiplechoice')], default='text', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='uiComponent',
            field=models.CharField(choices=[('field', 'field'), ('line', 'line'), ('textbox', 'textbox'), ('checkbox', 'checkbox'), ('dropdown', 'dropdown'), ('radioButton', 'radiobutton')], default='Field', max_length=100),
        ),
    ]
