# Generated by Django 3.1.6 on 2021-07-15 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210714_2325'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('network', 'organisation')},
        ),
    ]
