# Generated by Django 3.1.6 on 2021-07-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_networkmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkmember',
            name='role',
            field=models.IntegerField(choices=[(2, 'network admin'), (1, 'guest')], default=1),
        ),
    ]
