# Generated by Django 3.1.6 on 2021-07-20 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210716_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('denied', 'denied')], default='pending', max_length=100)),
                ('role', models.IntegerField(choices=[(2, 'organisation admin'), (1, 'guest')], default=1)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teammembers', to='core.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisationteams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
