# Generated by Django 3.1.6 on 2021-07-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_organisationmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationmember',
            name='role',
            field=models.IntegerField(choices=[(3, 'organisation admin'), (2, 'esea accountant'), (1, 'guest')], default=1),
        ),
    ]
