# Generated by Django 3.1.6 on 2021-07-25 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210722_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='survey',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.survey'),
            preserve_default=False,
        ),
    ]
