# Generated by Django 3.1.6 on 2021-07-26 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210725_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='indirectindicator',
            name='method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indirect_indicators', to='core.method'),
        ),
    ]
