# Generated by Django 3.1.6 on 2021-07-26 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_indirectindicator_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indirectindicator',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indirect_indicators', to='core.topic'),
        ),
    ]
