# Generated by Django 3.1.6 on 2021-07-26 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210726_1822'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indirectindicator',
            unique_together={('key', 'method')},
        ),
    ]
