# Generated by Django 3.1.6 on 2021-07-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210726_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directindicator',
            name='datatype',
            field=models.CharField(choices=[('text', 'text'), ('integer', 'Integer'), ('double', 'double'), ('date', 'date'), ('boolean', 'boolean'), ('singlechoice', 'singlechoice'), ('multiplechoice', 'multiplechoice')], default='text', max_length=50),
        ),
    ]
