# Generated by Django 3.1.6 on 2021-08-03 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20210802_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indirectindicator',
            name='formula',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='indirectindicator',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indirect_indicators', to='core.topic'),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='core.section'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_of_topic', to='core.topic'),
        ),
    ]
