# Generated by Django 3.1.6 on 2021-10-10 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20210803_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='network',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creatednetworks', to=settings.AUTH_USER_MODEL),
        ),
    ]
