# Generated by Django 3.1.6 on 2021-10-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20211018_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='image',
            field=models.ImageField(default='network/sustainability-circle.png', upload_to='network/'),
        ),
    ]
