# Generated by Django 3.1.6 on 2021-10-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_organisation_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='eseaaccount',
            name='deployed_to_respondents',
            field=models.BooleanField(default=False),
        ),
    ]
