# Generated by Django 3.1.6 on 2021-11-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_eseaaccount_deployed_to_respondents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indirectindicator',
            name='type',
            field=models.CharField(choices=[('performance', 'performance'), ('scoring', 'scoring')], default='SCORING', max_length=50),
        ),
    ]
