# Generated by Django 3.1.6 on 2021-11-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20211126_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
