# Generated by Django 3.1.6 on 2021-12-13 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='auditor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='directindicator',
            name='datatype',
            field=models.CharField(choices=[('text', 'text'), ('integer', 'integer'), ('double', 'double'), ('date', 'date'), ('boolean', 'boolean'), ('singlechoice', 'singlechoice'), ('multiplechoice', 'multiplechoice')], default='text', max_length=50),
        ),
        migrations.AlterField(
            model_name='organisationmember',
            name='role',
            field=models.IntegerField(choices=[(3, 'organisation admin'), (2, 'esea accountant'), (1, 'guest'), (4, 'auditor')], default=1),
        ),
    ]
