# Generated by Django 3.1.6 on 2022-02-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20220124_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='eseaaccount',
            name='verified_surveys',
            field=models.ManyToManyField(blank=True, related_name='verified_surveys', to='core.Survey'),
        ),
    ]
