# Generated by Django 3.1.6 on 2022-02-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_accountaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountaudit',
            name='assurance',
            field=models.CharField(blank=True, choices=[('limited', 'limited'), ('reasonable', 'reasonable'), ('assurance rejected', 'assurance rejected'), ('no assurance', 'no assurance')], max_length=100),
        ),
    ]
