# Generated by Django 3.1.6 on 2022-02-19 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20220219_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountaudit',
            name='auditors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
