# Generated by Django 3.1.6 on 2022-02-20 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20220220_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyaudit',
            name='account_audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_audits', to='core.accountaudit'),
        ),
    ]
