# Generated by Django 3.1.6 on 2022-03-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_accountaudit_assurance_declaration'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='auditstatus',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Awaiting Documentation', 'Awaiting Documentation'), ('Awaiting Correction', 'Awaiting Correction'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Open', max_length=100),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='doc_request_note',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='doc_upload_note',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='note',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='under_audit',
            field=models.BooleanField(default=False),
        ),
    ]
