# Generated by Django 3.1.6 on 2022-03-23 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20220323_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionresponse',
            name='auditstatus',
        ),
    ]
