# Generated by Django 3.1.6 on 2022-03-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_auto_20220328_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
