# Generated by Django 2.2.7 on 2020-07-02 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sea_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StakeholderGroup',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('method', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='sea_core.Method')),
            ],
            options={
                'verbose_name': 'stakeholder_group',
                'verbose_name_plural': 'stakeholder_groups',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=45)),
                ('rate', models.IntegerField(default=0)),
                ('anonymous', models.BooleanField()),
                ('method', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='sea_core.Method')),
                ('questions', models.ManyToManyField(
                    blank=True, to='sea_core.DirectIndicator')),
                ('stakeholder_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                        related_name='surveys', to='sea_core.StakeholderGroup')),
            ],
            options={
                'verbose_name': 'survey',
                'verbose_name_plural': 'surveys',
            },
        ),
    ]
