# Generated by Django 2.2.7 on 2020-07-16 12:24

from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    Question = apps.get_model("sea_core", "Question")
    for question in Question.objects.all():
        if question.type in ['SELECT', 'MULTI_SELECT', 'MULTI_CHECKBOX']:
            question.type = 'CHECKBOX'
            question.save()
        elif question.type == 'CHECKBOX':
            question.type = 'RADIO'
            question.save()


def reverse(apps, schema_editor):
    Question = apps.get_model("sea_core", "Question")
    for question in Question.objects.all():
        if question.type == 'CHECKBOX':
            question.type = 'SELECT'
            question.save()
        elif question.type == 'RADIO':
            question.type = 'CHECKBOX'
            question.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sea_core', '0004_auto_20200706_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='default',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='prefix',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='suffix',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('TEXT', 'text'), ('NUMBER', 'number'), (
                'RADIO', 'radio'), ('CHECKBOX', 'checkbox')], max_length=100),
        ),
        migrations.RunPython(forwards, reverse),
        migrations.AlterField(
            model_name='survey',
            name='method',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='sea_core.Method'),
        ),
    ]
